version: 2.1

executors:
  docker-executor:
    docker:
      - image: docker:18.06.3-ce-git
    working_directory: /work/workspace

  git-executor:
    docker:
      - image: alpine/git
    working_directory: /work/workspace

jobs:
  start:
    executor: git-executor
    steps:
      - attach_workspace:
          at: /work/workspace
      - checkout
      - persist_to_workspace:
          root: /work/workspace
          paths: .


  build-tests:
    executor: docker-executor
    steps:
      - setup_remote_docker

      - attach_workspace:
          at: /work/workspace

      - run: |
          docker build -f Dockerfile -t build_intel_detailed_router . ==target build_intel_detailed_router
          
      - run: |
          docker run --name cp --mount source=rVol,target=/run ubuntu
          docker run -it build_intel_detailed_router bash -c "cd analog && source /general/bin/activate && pytest --junit-xml=junit.xml && mkdir -p /test-reports/tests && cp /analog/junit.xml /test-reports/blocks"

  finish:
    executor: git-executor

    steps:
      - attach_workspace:
          at: /work/workspace

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

workflows:
  version: 2.1

  full:
    jobs:
      - start
      - build-tests:
          requires:
            - start 
      - finish:
          requires:
            - build-tests
